[package]
name = "router-claude"
version = "1.0.0"
description = "Claude Code Desktop model configuration manager"
authors = []
edition = "2021"

[lib]
name = "router_claude_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png", "tray-icon"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
